{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poktroll.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.className }}
  storageClassName: {{ .Values.persistence.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}