{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pocket.fullname" . }}
  labels:
      app: {{ include "pocket.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "pocket.fullname" . }}
  endpoints:
    - port: api
      interval: 30s
      path: /metrics
      params:
        format: [prometheus]
{{ end }}