{
  {
    - /*
    This template is a placeholder. We no longer include static config files with the chart.
    Users should either enable genesisRepo.downloadConfigs (default) or provide their own ConfigMaps.
    */ -,
  },
}
