{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-data" (include "poktrolld.fullname" .)) (ternary .Values.persistence.customName nil .Values.persistence.useCustomName) | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.className }}
  storageClassName: {{ .Values.persistence.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}