replicaCount: 1 # This number should probably always be 1, since validators can't share keys.

configsConfigMapName: poktrolld-configs # TODO(@okdas): provision in the chart
keysConfigMapName: poktrolld-keys # TODO(@okdas): provision in the chart

serviceMonitor:
  enabled: false

logs:
  level: info
  format: plain

development:
  delve:
    enabled: false
    laddr: :40004

image:
  repository: ghcr.io/pokt-network/poktrolld
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  rpcPort: 26657
  grpcPort: 9090
  timeout: 60000000000
  fee: 600000
  gas_limit: 6000000
prod:
  enabled: false
  namespace: ""
persistence:
  enabled: true
  className: ""
  size: 1Gi
  cleanupBeforeEachStart: false
  existingClaim: ""
scripts:
  enabled: true
podSecurityContext: {}
# allowPrivilegeEscalation: true
# capabilities:
#   add: ["SYS_PTRACE"]
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 8
#   memory: 16Gi
# requests:
#   cpu: 4
#   memory: 12Gi
