{{ $node_type := .Values.celestiaNode.type }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.celestiaNode.config.configmapName }}-{{ .Values.celestiaNode.type }}
  labels:
    {{- toYaml .Values.global.labels | trim | nindent 4 }}
data:
  {{- (.Files.Glob (printf "files/%s-node/config.toml" $node_type )).AsConfig | nindent 2 }}