{{- if not .Values.customConfigsConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocketd.fullname" . }}-configs
data:
  {{- $files := .Files.Glob "files/config/*" }}
  {{- range $path, $_ := $files }}
  {{- $name := base $path }}
  {{ $name }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
{{- end }}