# The service for P2P port is separated as users don't usually want to expose other ports.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocketd.fullname" . }}-p2p
  labels:
    {{- include "pocketd.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceP2P.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.serviceP2P.type }}
  {{- if or (eq .Values.serviceP2P.type "LoadBalancer") (eq .Values.serviceP2P.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.serviceP2P.externalTrafficPolicy }}
  {{- end }}
  internalTrafficPolicy: {{ .Values.serviceP2P.internalTrafficPolicy }}
  ports:
    - port: {{ .Values.serviceP2P.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "pocketd.selectorLabels" . | nindent 4 }}
