{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pocketd.fullname" . }}
  labels:
    {{- include "pocketd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pocketd.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      params:
        format: [prometheus]
{{ end }}