celestia-da:
  enabled: true

image:
  repository: ghcr.io/pokt-network/poktrolld
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  className: ""
  size: 1Gi
  existingClaim: ""

config:
  p2p:
    externalAddress: ""
    seedMode: false
    seeds: ""
    persistentPeers: ""
    unconditionalPeerIds: ""

rollkit:
  aggregator: true
  block_time: 1s

  # By default pointed to the svc created by the `celestia-da` chart.
  da_address: ""
  da_namespace: ""
  da_block_time: 15s
  da_gas_price: -1
  da_gas_multiplier: -1
  da_start_height: 1 # Assuming a default or starting value
  lazy_aggregator: false
  light: false
  trusted_hash: "" # Assuming an empty string as default, replace with actual hash if needed

serviceP2P:
  type: ClusterIP
  port: 26656

service:
  type: ClusterIP
  ports:
    rpc: 36657
    grpc: 36658

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    []
    # - name: rpc-endpoint.example.com
  tls:
    secretName: ""

# Name of the secret that contains `node_key.json` and `priv_validator_key.json`.
nodeKeysSecretName: ""

# TODO: Add pre-generated config maps when we have a stable public network.
genesis:
  # Name of the Config Map that containts the genesis.json of the network
  configMapName: ""
  configMapKey: genesis.json
