apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket.fullname" . }}
  labels:
    app: {{ include "pocket.fullname" . }}
spec:
  selector:
    app: {{ include "pocket.fullname" . }}
  ports:
    - protocol: TCP
      name: rpc
      port: 26657
      targetPort: 26657
    - protocol: TCP
      name: grpc
      port: 9090
      targetPort: 9090
    - port: 1317
      targetPort: api
      protocol: TCP
      name: api
