{{ if .Values.scripts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poktroll.fullname" . }}-scripts
data:
  dev.sh: |-
    #!/bin/sh

    echo "Running dev.sh"

    # Validator state is required to run the node, if it doesn't exist
    if [ ! -f /root/.pocket/data/priv_validator_state.json ]; then
      echo '{"height":"0","round":0,"step":0}' > /root/.pocket/data/priv_validator_state.json
      echo 'Generated new priv_validator_state.json'
    fi

    # ls -la /root/.pocket/config-src/
    mkdir -p /root/.pocket/config/
    cp -r -L /root/.pocket/config-src/* /root/.pocket/config/
    ls -la /root/.pocket/config/
    echo "\n/root/.pocket/config/priv_validator_key.json:"
    cat /root/.pocket/config/priv_validator_key.json
    echo "\n/root/.pocket/config/node_key.json:"
    cat /root/.pocket/config/node_key.json
    echo "\n/root/.pocket/config/genesis.json | jq '.validators':"
    cat /root/.pocket/config/genesis.json | jq '.validators'
  prod.sh: |-
    #!/bin/sh

    echo "Running prod.sh"

    # Make sure the data directory exists
    if [ ! -f /root/.pocket/data/priv_validator_state.json ]; then
      echo '{"height":"0","round":0,"step":0}' > /root/.pocket/data/priv_validator_state.json
    fi

    # Put a namespace id in place
    echo "{{ .Values.prod.namespace }}" > /root/.pocket/data/namespace-id
    NAMESPACE=$(cat /root/.pocket/data/namespace-id)

    if [ ! -f /root/.pocket/data/da-block-height ]; then
      curl -s https://rpc-mocha.pops.one/block |jq -r '.result.block.header.height' > /root/.pocket/data/da-block-height
    fi
    DA_BLOCK_HEIGHT=$(cat /root/.pocket/data/da-block-height)

    mkdir -p /root/.pocket/config/
    cp -r -L /root/.pocket/config-src/* /root/.pocket/config/
    ls -la /root/.pocket/config/
    echo "\n/root/.pocket/config/priv_validator_key.json:"
    cat /root/.pocket/config/priv_validator_key.json
    echo "\n/root/.pocket/config/node_key.json:"
    cat /root/.pocket/config/node_key.json
    echo "\n/root/.pocket/config/genesis.json | jq '.validators':"
    cat /root/.pocket/config/genesis.json | jq '.validators'
{{ end }}
